nobiot/org-transclusion

- org-transclusion.el
This is features added and showed with demo#3.
1. `otc:` link type supports `file.org::*headline` and `file.org::paragraph`
Variable `org-transclusion-add-at-point-functions` to control transclusion behaviour
2. Translude Org Mode standard `[[file:path/to/file.org::*headline][support headline]]`
Variable `org-transclusion-add-org-link-at-point-function` to control transclusion behaviour
3. New issue: A buffer can transclude overlapping regions
> Add feature to add transclusion for standard org link types: heading Demo #3

- README.md
Related to #14:
An experimental feature has been merged. Now the transcluded source text content "adapts" the headline level of its subtrees to its embedded environment in the transclusion buffer. It's quite mouthful, but see the logic below. It should be the same as how refill / archive work in Org Mode (if I am not mistaken).
Logic is as follows (from documentation of `org-paste-subtree` ):
```
[... omitted ... ] [T]he new level is derived from the *visible* headings
before and after the insertion point, and taken to be the inferior headline
level of the two.  So if the previous visible heading is level 3 and the
next is level 4 (or vice versa), level 4 will be used for insertion.
This makes sure that the subtree remains an independent subtree and does
not swallow low level entries.
``` …
> Add explanation of org-transclusion-paste-subtree

- README.md
- org-transclusion.el
After the v0.0.5, a feature to include the first section (section before the first headline) is added. It is toggled via cusotmizing variable `org-transclusion-include-first-section`. Its default value is `nil`. Set it to `t` to transclude the first section.
Motivation: #25 
But it does not fix the root cause of the error -- when `tc-content` is `""` it will still emits an error and does bag things...
> Add feature to include first section for Org file

- org-transclusion.el
The immediate issue was that org-roam-id-open "overrides" the
org-open-at-point.  This is done via Org Mode's hook
`org-open-at-point-functions` and should be expected.
This is a good opportunity to refactor the way `org-transclusion-open-link-*` works.
Now I can use `org-open-at-point-functions` hook, and can remove the advice-add.
`advice-add` is not a good solution as it is a global change, where
Org-transclusion is buffer local.  With the hook, it can be a buffer local.
This commit is a WIP; need to clean up the superflous functions I added before realising hook is a better solution than advice.
> Fix org-roam-id-open (WIP)

- README.md
First great thanks for creating this package!
I have been impressed with what `org-transclusion` can achieve, by the demonstration videos and the presentation in EmacsConf2020. I watched all the YouTube videos, and decided to give it a try. Unfortunately, I tried it several times in the past few weeks, and it just refused to work. Today, I decided to look into the code to see what's wrong. In a couple of minutes, I noticed a test of `(bolp)`. So transclusion links will only work if there is no space before it. Sure enough, this is documented in README and is for good reason. I am only making the text bold so no other people will let it go unnoticed, like I did.
> Emphasize that no space before link is allowed

- org-transclusion.el
- test/unit-tests.el
Hi @nobiot!
First of all thanks a lot for this amazing package.
I've started using it today and just noticed that when an org file is encrypted (i.e. [filename].org.gpg) it behaves unexpectedly. From what I observed, when trying to transclude a heading from an encrypted org file, the entire contents of the file get included instead of the linked heading. Note that I'm using org-roam with encryption so if there are people like me out there with the same set up they might run into the same problem.
After looking into it, I noticed that a file link from an encrypted org file is treated as others-default because `org-transclusion-org-file-p` ([this one](https://github.com/nobiot/org-transclusion/blob/7b141a96d7793124e0afa1a2c0856ee57e9967aa/org-transclusion.el#L1219)) returns nil, because it …
> handle encrypted org files

- README.org
Hi @nobiot 
It's me again :) 
I just noticed, in the README, that some command names appears to be out of date.
It looks like you've fixed most of them after the v0.2.0 version bump so I could only find a few of them.
I've also fixed some alignment in case you were wondering what was happening in the last hunk around line 344.
Anyways I hope it helps! 
Thanks
> Correct command names in README to match v0.2.0

- org-transclusion.el
Ignoring cleanup process when isn't needed fixes #94.
> fix: cleanup only if there were activated transclusion

- README.org
- org-transclusion-src-lines.el
This PR is intended to address #92.
As of 29 Oct 2020, still early, but it works with my minimal testing.
> Add `:end` prop for search text string to indicate end of the src/text source to transclude 

- org-transclusion-src-lines.el
Which worked before the commit of
https://github.com/nobiot/org-transclusion/commit/49dc7fdaa03d26a841a03809571c21480e2c277a,
but advent of which commit, it has broken.
Specifically, now end line specification works as an offset from starting line.
I.e., `:lines 3-5` specifies the region of line 3 to 3 + 5, not line 3 to 5.
> Fix the reference point for line end specification

- org-transclusion.el
- test/test-2.1-lines.org
The keyword (including #+transclude) element includes the affiliated
keywords (the keywords before #+transclude) such as #+name, #+caption. Thus,
removing the whole element from beg to end also removes them all. Changing the
region's beginning to post-affiliated includes only the #+transclude keyword,
keeping the affiliated keywords as they are.
> fix:#115 Allow adding #+name, etc. before #+transclude keyword

- org-transclusion.el
This makes available the whole keybindings of Org mode even whern org-transclusion-mode is running.
The keybindings of org-transclusion override Org mode map (that's how keybinding inheritance works)
I followed the guide at
https://www.gnu.org/software/emacs/manual/html_node/elisp/Inheritance-and-Keymaps.html
because I really cannot enjoy an Org file without most of Org key
bindings available :)
Happy to close it if that is not what you want for your mode.
> Use org-mode keymap as a parent to reuse binding

- NEWS
- org-transclusion.el
- test/test-2.0.org
For non-Org files only, now the transcluded text respects the indent level of
the #+transclude keyword.  This does not affect Org files.
> fix:#131: Transclusion respects indent level for non-Org text files

- org-transclusion.el
- test/test-2.0.org
- New command 'org-transclusion-detach' can be used on the transclusion
at point. It turns it into a normal, edtitable text content.
You can undo this operation.
In addition, you can press 'C-d' directly on the transclusion at point
to detach it.  This is because the command is bound to 'C-d' by
default in 'org-transclusion-map'.
- 'org-transclusion-refresh' now accepts universal argument such as
'C-u M-x org-transclusion-refresh' and detaches the transclusion at
point.
- 'org-transclusion-add' now accepts universal argument such as 'C-u M-x
org-transclusion-add' and copies the source content rather than
transclude it.
You can undo this operation.
- Limitation: Undo detach does not add the overlay back on the
source. This should not break any feature. You can safely refresh the …
> Dev/detach to address #152

- test/unit-tests.el
Resolves:
unit-tests.el:8:19: Warning: the function `org-transclusion-org-file-p' is not known to be defined.
> fix: (unit-tests.el) require org-transclusion

- org-transclusion-src-lines.el
This ensures that org-transclusion-content-format is defined.
(my FSF copyright assignment paperwork has been accepted)
> fix: (org-transclusion-src-lines.el) require org-transclusion

- org-transclusion.el
The default setting of `org-link-search-must-match-exact-headline`
causes Emacs to prompt the user to create a new heading when a link
target is not found.
This commit temporarily overrides the default setting to signal an
error when no headline exactly matches the link target.  Since errors
are demoted, this skips the failed transclusion.
However, if the user has set
`org-link-search-must-match-exact-headline` to perform a fuzzy search
for link targets, we don't override the option.
> Don't ever prompt to create a headline when transcluding 

- org-transclusion-src-lines.el
- org-transclusion.el
- test/things-at-point-dir/story.txt
- text-clone.el
This hook variable was renamed in [1: fe90cab95].
1: 2022-09-06 fe90cab9564bd6fa08c9abe0882e0e06cc5626f9
lisp/ox.el: Rename abnormal hook names to end with "-functions"
> Use org-export-before-processing-functions if available

- org-transclusion.el
In tandem with #209, this commit allows for a transclusion workflow with `hyper://` links (see [hyperdrive.el](https://git.sr.ht/~ushin/hyperdrive.el/tree/org-transclusion/item/hyperdrive-org-transclusion.el)) or `http://` links.
> chg: Allow making transclusion links from any protocol link

- org-transclusion-html.el
Some org-transclusion features for Org mode, such as :level, expect tc-type to begin with "org".  See `org-transclusion-type-is-org` and its usage for details.
> Fix: (org-transclusion-add-html-file) Use "org-html-file" tc-type

- org-transclusion-html.el
Match the convention that the functions/variable defined in a file be prefixed with the file's basename.
> chg: (org-transclusion-add-functions) Rename hook

- org-transclusion.el
I'm glad I caught this before the release :)
> fix: extension name typo

- NEWS
- org-transclusion.el
Technically, this function is not a callback function, although in both org-transclusion-http and hyperdrive-org-transclusion, it is called from within asynchronous callback functions.
If we want to change its name, better to do it now than after v1.4.0.
> chg: Rename -add-callback to -add-payload

- org-transclusion.el
Please see commits for details.  If you don't like a particular change, I can
drop it for you.
> Various minor cleanup

- NEWS
- org-transclusion-src-lines.el
- org-transclusion.el
- test/test-2.0.org
Fixing a long-lasting (issue open since March 2023, but it had been an known issue before it) issue that was difficult to reproduce.
The fix is to stop using the text-properties of the transclusion that hold markers of beginning and ending points of itself, which is meant to remember and indicate its own the location; or the range of "this" transclusion at point. The text-properties are named `org-transclusion-beg-mkr' and `org-transclusion-end-mkr'. They are replaced with use of a new text-property `org-transclusion-id' and function `org-transclusion-at-point'. This new function uses `prop-match' with `org-transclusion-id' to identify the range of "this" transclusion at point only when it is needed, thus eliminating the need for memorizing it as a pair of markers.
Stable reproduction was …
> fix: #177 Infinite loop when saving buffer with transclusions

- org-transclusion.el
In [1: f6fd666] we stopped using this lexical variable.
> fix: Remove unused lexical variable

- org-transclusion.el
Just some minor fixes I never submitted as a PR.  Thanks!
> refactor: Minor tidying up
